import { Component, OnInit } from "@angular/core";
import { RushingModel } from "../model/rushing.model";
import { RushingService } from "./rushing.service";
import { ViewChild } from "@angular/core";
import { Table } from "primeng/table";

@Component({
  selector: 'rushing-table',
  templateUrl: './rushing-table.component.html',
  styleUrls: ['./rushing-table.component.scss'],
  providers: []
})

export class RushingTable implements OnInit {
  rushingTableDataSource: RushingModel[];
  rushingColumnHeaders: any[];
  teams: any[];
  positions: any[];
  loading: boolean = true;

  @ViewChild('dt') table: Table;
  constructor(private rushingService: RushingService) { }

  ngOnInit(): void {
    this.rushingService.getRushing().subscribe(data =>
      this.rushingTableDataSource = data
    );
    this.loading = false;

    this.teams = [
      { label: 'ALL', value: '', },
      { label: 'ATL', value: 'ATL' },
      { label: 'ARI', value: 'ARI' },
      { label: 'BAL', value: 'BAL' },
      { label: 'BUF', value: 'BUF' },
      { label: 'CAR', value: 'CAR' },
      { label: 'CHI', value: 'CHI' },
      { label: 'CIN', value: 'CIN' },
      { label: 'CLE', value: 'CLE' },
      { label: 'DAL', value: 'DAL' },
      { label: 'DEN', value: 'DEN' },
      { label: 'DET', value: 'DET' },
      { label: 'GB', value: 'GB' },
      { label: 'HOU', value: 'HOU' },
      { label: 'IND', value: 'IND' },
      { label: 'JAX', value: 'JAX' },
      { label: 'KC', value: 'KC' },
      { label: 'LA', value: 'LA' },
      { label: 'MIA', value: 'MIA' },
      { label: 'MIN', value: 'MIN' },
      { label: 'NE', value: 'NE' },
      { label: 'NO', value: 'NO' },
      { label: 'NYG', value: 'NYG' },
      { label: 'NYJ', value: 'NYJ' },
      { label: 'OAK', value: 'OAK' },
      { label: 'PHI', value: 'PHI' },
      { label: 'PIT', value: 'PIT' },
      { label: 'SD', value: 'SD' },
      { label: 'SEA', value: 'SEA' },
      { label: 'SF', value: 'SF' },
      { label: 'TEN', value: 'TEN' },
      { label: 'TB', value: 'TB' },
      { label: 'Was', value: 'Was' },
    ];


    this.positions = [
      { label: 'ALL', value: '', },
      { label: 'RB', value: 'RB' },
      { label: 'QB', value: 'QB' },
      { label: 'WR', value: 'WR' },
      { label: 'P', value: 'P' },
      { label: 'TE', value: 'TE' },
      { label: 'FB', value: 'FB' },
      { label: 'SS', value: 'SS' },
      { label: 'NT', value: 'NT' },

    ];

    // this.rushingTableDataSource = [
    //   {
    //     "id": "61245a23dd52398d160c07c2",
    //     "Player": "Johnny Holton",
    //     "Team": "OAK",
    //     "Pos": "WR",
    //     "Att": 6,
    //     "AttPerG": 0.4,
    //     "Yds": 43,
    //     "Avg": 7.2,
    //     "YdsPerG": 2.9,
    //     "TD": 0,
    //     "Lng": "29",
    //     "first": 2,
    //     "firstPercentage": 33.3,
    //     "twentyPlus": 1,
    //     "fortyPlus": 0,
    //     "FUM": 1
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Dion Lewis",
    //     "Team": "NE",
    //     "Pos": "RB",
    //     "Att": 64,
    //     "AttPerG": 9.1,
    //     "Yds": 283,
    //     "Avg": 4.4,
    //     "YdsPerG": 40.4,
    //     "TD": 0,
    //     "Lng": "15",
    //     "first": 14,
    //     "firstPercentage": 21.9,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 1
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "James White",
    //     "Team": "NE",
    //     "Pos": "RB",
    //     "Att": 39,
    //     "AttPerG": 2.4,
    //     "Yds": 166,
    //     "Avg": 4.3,
    //     "YdsPerG": 10.4,
    //     "TD": 0,
    //     "Lng": "16",
    //     "first": 8,
    //     "firstPercentage": 20.5,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Mack Brown",
    //     "Team": "WAS",
    //     "Pos": "RB",
    //     "Att": 8,
    //     "AttPerG": 0.9,
    //     "Yds": 82,
    //     "Avg": 10.3,
    //     "YdsPerG": 9.1,
    //     "TD": 1,
    //     "Lng": "61T",
    //     "first": 1,
    //     "firstPercentage": 12.5,
    //     "twentyPlus": 1,
    //     "fortyPlus": 1,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "David Fales",
    //     "Team": "CHI",
    //     "Pos": "QB",
    //     "Att": 1,
    //     "AttPerG": 1,
    //     "Yds": 0,
    //     "Avg": 0,
    //     "YdsPerG": 0,
    //     "TD": 0,
    //     "Lng": "0",
    //     "first": 0,
    //     "firstPercentage": 0,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 1
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Devontae Booker",
    //     "Team": "DEN",
    //     "Pos": "RB",
    //     "Att": 174,
    //     "AttPerG": 10.9,
    //     "Yds": 612,
    //     "Avg": 3.5,
    //     "YdsPerG": 38.2,
    //     "TD": 4,
    //     "Lng": "18",
    //     "first": 30,
    //     "firstPercentage": 17.2,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 2
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Orleans Darkwa",
    //     "Team": "NYG",
    //     "Pos": "RB",
    //     "Att": 30,
    //     "AttPerG": 3,
    //     "Yds": 111,
    //     "Avg": 3.7,
    //     "YdsPerG": 11.1,
    //     "TD": 2,
    //     "Lng": "17",
    //     "first": 7,
    //     "firstPercentage": 23.3,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Marc Mariani",
    //     "Team": "TEN",
    //     "Pos": "WR",
    //     "Att": 1,
    //     "AttPerG": 0.1,
    //     "Yds": 15,
    //     "Avg": 15,
    //     "YdsPerG": 0.9,
    //     "TD": 0,
    //     "Lng": "15",
    //     "first": 1,
    //     "firstPercentage": 100,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "C.J. Spiller",
    //     "Team": "NYJ",
    //     "Pos": "RB",
    //     "Att": 3,
    //     "AttPerG": 0.8,
    //     "Yds": 9,
    //     "Avg": 3,
    //     "YdsPerG": 2.2,
    //     "TD": 0,
    //     "Lng": "4",
    //     "first": 2,
    //     "firstPercentage": 66.7,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Will Fuller",
    //     "Team": "HOU",
    //     "Pos": "WR",
    //     "Att": 1,
    //     "AttPerG": 0.1,
    //     "Yds": -3,
    //     "Avg": -3,
    //     "YdsPerG": -0.2,
    //     "TD": 0,
    //     "Lng": "3",
    //     "first": 0,
    //     "firstPercentage": 0,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Isaiah Crowell",
    //     "Team": "CLE",
    //     "Pos": "RB",
    //     "Att": 198,
    //     "AttPerG": 12.4,
    //     "Yds": 952,
    //     "Avg": 4.8,
    //     "YdsPerG": 59.5,
    //     "TD": 7,
    //     "Lng": "85T",
    //     "first": 45,
    //     "firstPercentage": 22.7,
    //     "twentyPlus": 8,
    //     "fortyPlus": 3,
    //     "FUM": 2
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Kenyan Drake",
    //     "Team": "MIA",
    //     "Pos": "RB",
    //     "Att": 33,
    //     "AttPerG": 2.1,
    //     "Yds": 179,
    //     "Avg": 5.4,
    //     "YdsPerG": 11.2,
    //     "TD": 2,
    //     "Lng": "45T",
    //     "first": 9,
    //     "firstPercentage": 27.3,
    //     "twentyPlus": 1,
    //     "fortyPlus": 1,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Tommylee Lewis",
    //     "Team": "NO",
    //     "Pos": "WR",
    //     "Att": 3,
    //     "AttPerG": 0.2,
    //     "Yds": 11,
    //     "Avg": 3.7,
    //     "YdsPerG": 0.9,
    //     "TD": 0,
    //     "Lng": "7",
    //     "first": 1,
    //     "firstPercentage": 33.3,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Larry Fitzgerald",
    //     "Team": "ARI",
    //     "Pos": "WR",
    //     "Att": 2,
    //     "AttPerG": 0.1,
    //     "Yds": 5,
    //     "Avg": 2.5,
    //     "YdsPerG": 0.3,
    //     "TD": 0,
    //     "Lng": "4",
    //     "first": 0,
    //     "firstPercentage": 0,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Dion Lewis",
    //     "Team": "NE",
    //     "Pos": "RB",
    //     "Att": 64,
    //     "AttPerG": 9.1,
    //     "Yds": 283,
    //     "Avg": 4.4,
    //     "YdsPerG": 40.4,
    //     "TD": 0,
    //     "Lng": "15",
    //     "first": 14,
    //     "firstPercentage": 21.9,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 1
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c2",
    //     "Player": "Johnny Holton",
    //     "Team": "OAK",
    //     "Pos": "WR",
    //     "Att": 6,
    //     "AttPerG": 0.4,
    //     "Yds": 43,
    //     "Avg": 7.2,
    //     "YdsPerG": 2.9,
    //     "TD": 0,
    //     "Lng": "29",
    //     "first": 2,
    //     "firstPercentage": 33.3,
    //     "twentyPlus": 1,
    //     "fortyPlus": 0,
    //     "FUM": 1
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Dion Lewis",
    //     "Team": "NE",
    //     "Pos": "RB",
    //     "Att": 64,
    //     "AttPerG": 9.1,
    //     "Yds": 283,
    //     "Avg": 4.4,
    //     "YdsPerG": 40.4,
    //     "TD": 0,
    //     "Lng": "15",
    //     "first": 14,
    //     "firstPercentage": 21.9,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 1
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "James White",
    //     "Team": "NE",
    //     "Pos": "RB",
    //     "Att": 39,
    //     "AttPerG": 2.4,
    //     "Yds": 166,
    //     "Avg": 4.3,
    //     "YdsPerG": 10.4,
    //     "TD": 0,
    //     "Lng": "16",
    //     "first": 8,
    //     "firstPercentage": 20.5,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Mack Brown",
    //     "Team": "WAS",
    //     "Pos": "RB",
    //     "Att": 8,
    //     "AttPerG": 0.9,
    //     "Yds": 82,
    //     "Avg": 10.3,
    //     "YdsPerG": 9.1,
    //     "TD": 1,
    //     "Lng": "61T",
    //     "first": 1,
    //     "firstPercentage": 12.5,
    //     "twentyPlus": 1,
    //     "fortyPlus": 1,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "David Fales",
    //     "Team": "CHI",
    //     "Pos": "QB",
    //     "Att": 1,
    //     "AttPerG": 1,
    //     "Yds": 0,
    //     "Avg": 0,
    //     "YdsPerG": 0,
    //     "TD": 0,
    //     "Lng": "0",
    //     "first": 0,
    //     "firstPercentage": 0,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 1
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Devontae Booker",
    //     "Team": "DEN",
    //     "Pos": "RB",
    //     "Att": 174,
    //     "AttPerG": 10.9,
    //     "Yds": 612,
    //     "Avg": 3.5,
    //     "YdsPerG": 38.2,
    //     "TD": 4,
    //     "Lng": "18",
    //     "first": 30,
    //     "firstPercentage": 17.2,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 2
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Orleans Darkwa",
    //     "Team": "NYG",
    //     "Pos": "RB",
    //     "Att": 30,
    //     "AttPerG": 3,
    //     "Yds": 111,
    //     "Avg": 3.7,
    //     "YdsPerG": 11.1,
    //     "TD": 2,
    //     "Lng": "17",
    //     "first": 7,
    //     "firstPercentage": 23.3,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Marc Mariani",
    //     "Team": "TEN",
    //     "Pos": "WR",
    //     "Att": 1,
    //     "AttPerG": 0.1,
    //     "Yds": 15,
    //     "Avg": 15,
    //     "YdsPerG": 0.9,
    //     "TD": 0,
    //     "Lng": "15",
    //     "first": 1,
    //     "firstPercentage": 100,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "C.J. Spiller",
    //     "Team": "NYJ",
    //     "Pos": "RB",
    //     "Att": 3,
    //     "AttPerG": 0.8,
    //     "Yds": 9,
    //     "Avg": 3,
    //     "YdsPerG": 2.2,
    //     "TD": 0,
    //     "Lng": "4",
    //     "first": 2,
    //     "firstPercentage": 66.7,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Will Fuller",
    //     "Team": "HOU",
    //     "Pos": "WR",
    //     "Att": 1,
    //     "AttPerG": 0.1,
    //     "Yds": -3,
    //     "Avg": -3,
    //     "YdsPerG": -0.2,
    //     "TD": 0,
    //     "Lng": "3",
    //     "first": 0,
    //     "firstPercentage": 0,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Isaiah Crowell",
    //     "Team": "CLE",
    //     "Pos": "RB",
    //     "Att": 198,
    //     "AttPerG": 12.4,
    //     "Yds": 952,
    //     "Avg": 4.8,
    //     "YdsPerG": 59.5,
    //     "TD": 7,
    //     "Lng": "85T",
    //     "first": 45,
    //     "firstPercentage": 22.7,
    //     "twentyPlus": 8,
    //     "fortyPlus": 3,
    //     "FUM": 2
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Kenyan Drake",
    //     "Team": "MIA",
    //     "Pos": "RB",
    //     "Att": 33,
    //     "AttPerG": 2.1,
    //     "Yds": 179,
    //     "Avg": 5.4,
    //     "YdsPerG": 11.2,
    //     "TD": 2,
    //     "Lng": "45T",
    //     "first": 9,
    //     "firstPercentage": 27.3,
    //     "twentyPlus": 1,
    //     "fortyPlus": 1,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Tommylee Lewis",
    //     "Team": "NO",
    //     "Pos": "WR",
    //     "Att": 3,
    //     "AttPerG": 0.2,
    //     "Yds": 11,
    //     "Avg": 3.7,
    //     "YdsPerG": 0.9,
    //     "TD": 0,
    //     "Lng": "7",
    //     "first": 1,
    //     "firstPercentage": 33.3,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Larry Fitzgerald",
    //     "Team": "ARI",
    //     "Pos": "WR",
    //     "Att": 2,
    //     "AttPerG": 0.1,
    //     "Yds": 5,
    //     "Avg": 2.5,
    //     "YdsPerG": 0.3,
    //     "TD": 0,
    //     "Lng": "4",
    //     "first": 0,
    //     "firstPercentage": 0,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 0
    //   },
    //   {
    //     "id": "61245a23dd52398d160c07c4",
    //     "Player": "Dion Lewis",
    //     "Team": "NE",
    //     "Pos": "RB",
    //     "Att": 64,
    //     "AttPerG": 9.1,
    //     "Yds": 283,
    //     "Avg": 4.4,
    //     "YdsPerG": 40.4,
    //     "TD": 0,
    //     "Lng": "15",
    //     "first": 14,
    //     "firstPercentage": 21.9,
    //     "twentyPlus": 0,
    //     "fortyPlus": 0,
    //     "FUM": 1
    //   }
    // ];

    this.rushingColumnHeaders = [
      { field: "Player", header: "Player Name", isVisible: true, width: "10%" },
      { field: "Team", header: "Team", isVisible: true, width: "10%" },
      { field: "Pos", header: "Position", isVisible: true, width: "10%" },
      { field: "Att", header: "Att", isVisible: true, width: "6%" },
      { field: "AttPerG", header: "Att/G", isVisible: true, width: "6%" },
      { field: "Yds", header: "Yds", isVisible: true, width: "6%" },
      { field: "Avg", header: "Avg", isVisible: true, width: "6%" },
      { field: "YdsPerG", header: "Yds/G", isVisible: true, width: "6%" },
      { field: "TD", header: "TD", isVisible: true, width: "6%" },
      { field: "Lng", header: "Lng", isVisible: true, width: "6%" },
      { field: "first", header: "1st", isVisible: true, width: "6%" },
      { field: "firstPercentage", header: "1st%", isVisible: true, width: "6%" },
      { field: "twentyPlus", header: "20+", isVisible: true, width: "6%" },
      { field: "fortyPlus", header: "40+", isVisible: true, width: "5%" },
      { field: "FUM", header: "FUM", isVisible: true, width: "5%" },
    ];

  }

}